name: Build
on:
  # Push events to matching v*, i.e. v1.0, v20.15.10
  push:
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: plex-discord
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create GitHub release
        id: ghrelease
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
